// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9O-iuFOkTO553A5wJbRpa7tzYYQgMNs',
    appId: '1:1041949970194:web:5b90a9a46c653f3dbfedcb',
    messagingSenderId: '1041949970194',
    projectId: 'fir-auth-si6b',
    authDomain: 'fir-auth-si6b.firebaseapp.com',
    storageBucket: 'fir-auth-si6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAww6bAqBUTfkEH8LTwdPi_FKH1gOJuxAI',
    appId: '1:1041949970194:android:5daaa585a5725da6bfedcb',
    messagingSenderId: '1041949970194',
    projectId: 'fir-auth-si6b',
    storageBucket: 'fir-auth-si6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxcR6k-JMjqAVzxzk5tWFnrJAhNLbQKiI',
    appId: '1:1041949970194:ios:7d6ae2d021ac4c7bbfedcb',
    messagingSenderId: '1041949970194',
    projectId: 'fir-auth-si6b',
    storageBucket: 'fir-auth-si6b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );
}
